### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by fobos531** [teleshoes/s5-config#1]
Hello.
First of all, this not a bug report. 
I'm sorry to disturb you like this with questions. I had to resort to this since there isn't a private messaging feature on GitHub. I have a question regarding tpacpi-bat. Following your instructions and executing the install.pl script, I get the following error: 
"make -C /lib/modules/4.8.8-2-ARCH/build M=/tmp/acpi_call modules
make[1]: Entering directory '/usr/lib/modules/4.8.8-2-ARCH/build'
make[1]: *** No rule to make target 'modules'.  Stop.
make[1]: Leaving directory '/usr/lib/modules/4.8.8-2-ARCH/build'
make: *** [Makefile:8: default] Error 2
error running 'make'
"

Do you know what might be the issue? Please don't ignore this message of mine, as I'm in need of help. 

Thanks.

**Comment by teleshoes** [comment]
lol, is there some reason you opened this issue against my cellphone config repo instead of opening it against tpacpi-bat?

i dont know whats wrong, but the problem is in building acpi_call, which is a dependency of tpacpi-bat but is not part of tpacpi-bat. try installing that separately to isolate the issue.
